version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "dev"]

  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "build", "&&", "pnpm", "start"]
